import type { AnalysisResponse, ClauseResult } from '../api/types';
import { scoreToHex, SEVERITY_TOKENS, overallScoreToVerdict } from './riskColors';

const CELL = 36;
const GAP  = 6;
const COLS = 10;
const PAD  = 32;

export function exportHeatmapPNG(analysis: AnalysisResponse, fileName: string): void {
  const clauses = analysis.clauses;
  const rows    = Math.ceil(clauses.length / COLS);
  const W       = COLS * (CELL + GAP) - GAP + PAD * 2;
  const H       = rows  * (CELL + GAP) - GAP + PAD * 2 + 160;

  const canvas  = document.createElement('canvas');
  canvas.width  = W * 2;
  canvas.height = H * 2;
  const ctx     = canvas.getContext('2d')!;
  ctx.scale(2, 2);

  ctx.fillStyle = '#0C0E12';
  ctx.fillRect(0, 0, W, H);

  ctx.fillStyle = '#E8EAF0';
  ctx.font      = '600 15px monospace';
  ctx.fillText('CONTRACT RISK HEATMAP', PAD, PAD + 16);

  ctx.fillStyle = '#8B91A8';
  ctx.font      = '400 11px monospace';
  ctx.fillText(fileName, PAD, PAD + 34);

  const verdict  = overallScoreToVerdict(analysis.overall_score);
  const sevColor = analysis.overall_score >= 75 ? '#F7C1C1'
                 : analysis.overall_score >= 55 ? '#F09595'
                 : analysis.overall_score >= 30 ? '#FAC775' : '#C0DD97';
  ctx.fillStyle  = sevColor;
  ctx.font       = '600 13px monospace';
  ctx.fillText(`Score: ${analysis.overall_score}/100 — ${verdict}`, PAD, PAD + 56);

  const counts   = {
    critical: clauses.filter(c => c.severity === 'critical').length,
    high:     clauses.filter(c => c.severity === 'high').length,
    medium:   clauses.filter(c => c.severity === 'medium').length,
    low:      clauses.filter(c => c.severity === 'low').length,
  };
  ctx.fillStyle  = '#4A5068';
  ctx.font       = '400 10px monospace';
  ctx.fillText(
    `${counts.critical} critical  ${counts.high} high  ${counts.medium} medium  ${counts.low} low`,
    PAD, PAD + 74,
  );

  const gridTop = PAD + 90;
  clauses.forEach((clause, i) => {
    const col = i % COLS;
    const row = Math.floor(i / COLS);
    const x   = PAD + col * (CELL + GAP);
    const y   = gridTop + row * (CELL + GAP);
    const hex = scoreToHex(clause.score);

    ctx.fillStyle = hex;
    ctx.beginPath();
    ctx.roundRect(x, y, CELL, CELL, 6);
    ctx.fill();

    ctx.fillStyle = '#0C0E12';
    ctx.font      = '600 10px monospace';
    ctx.textAlign = 'center';
    ctx.fillText(String(clause.score), x + CELL / 2, y + CELL / 2 + 4);
    ctx.textAlign = 'left';
  });

  const legendY = gridTop + rows * (CELL + GAP) + 16;
  ([
    { label: 'Low 1-3',       color: '#C0DD97' },
    { label: 'Medium 4-6',    color: '#FAC775' },
    { label: 'High 7-8',      color: '#F09595' },
    { label: 'Critical 9-10', color: '#F7C1C1' },
  ] as const).forEach((l, i) => {
    const lx = PAD + i * 110;
    ctx.fillStyle = l.color;
    ctx.beginPath();
    ctx.roundRect(lx, legendY, 12, 12, 3);
    ctx.fill();
    ctx.fillStyle = '#8B91A8';
    ctx.font      = '400 10px monospace';
    ctx.fillText(l.label, lx + 16, legendY + 10);
  });

  ctx.fillStyle = '#2A2F3D';
  ctx.font      = '400 9px monospace';
  ctx.fillText('Generated by ContractRisk Heatmap', PAD, H - 12);

  const link    = document.createElement('a');
  link.download = `risk-heatmap-${Date.now()}.png`;
  link.href     = canvas.toDataURL('image/png');
  link.click();
}

export function exportJSON(analysis: AnalysisResponse, fileName: string): void {
  const data = JSON.stringify(
    { file: fileName, generated: new Date().toISOString(), ...analysis },
    null, 2,
  );
  const blob = new Blob([data], { type: 'application/json' });
  const link = document.createElement('a');
  link.download = `risk-report-${Date.now()}.json`;
  link.href     = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}