import type { AnalysisResponse } from '../api/types';

export const MOCK_ANALYSIS: AnalysisResponse = {
  overall_score: 68,
  pdf_id: 'mock-pdf-001',
  clauses: [
    {
      clause_id: 'c-01',
      text: 'Vendor may unilaterally modify pricing with 30 days written notice.',
      page: 2,
      score: 8,
      category: 'payment',
      severity: 'high',
      reasoning: 'Allows vendor to raise prices with minimal notice.',
      suggestions: [
        'Price increases shall not exceed 5% annually without mutual written agreement.',
      ],
    },
    {
      clause_id: 'c-02',
      text: 'This agreement auto-renews annually unless cancelled 90 days before term end.',
      page: 2,
      score: 7,
      category: 'auto_renewal',
      severity: 'high',
      reasoning: 'Long cancellation window makes it easy to miss and be locked in.',
      suggestions: ['Reduce cancellation notice period to 30 days.'],
    },
    {
      clause_id: 'c-03',
      text: 'Customer grants Vendor a perpetual, irrevocable license to use aggregated data.',
      page: 3,
      score: 10,
      category: 'data',
      severity: 'critical',
      reasoning: 'Perpetual and irrevocable data rights are unusually broad.',
      suggestions: [
        'License to aggregated data should be limited to the term of the agreement.',
        'Add explicit data deletion obligations within 30 days of termination.',
      ],
    },
    {
      clause_id: 'c-04',
      text: 'Vendor total liability shall not exceed one month of fees paid.',
      page: 5,
      score: 9,
      category: 'liability',
      severity: 'critical',
      reasoning: 'Extremely low liability cap disproportionate to potential damages.',
      suggestions: ['Liability cap should be the greater of 12 months fees or actual damages.'],
    },
    {
      clause_id: 'c-05',
      text: 'Either party may terminate for convenience with 30 days written notice.',
      page: 6,
      score: 3,
      category: 'termination',
      severity: 'low',
      reasoning: 'Standard termination clause; no unusual risk.',
      suggestions: [],
    },
    {
      clause_id: 'c-06',
      text: 'Customer retains all IP rights in data submitted to the platform.',
      page: 7,
      score: 2,
      category: 'ip',
      severity: 'low',
      reasoning: 'Clear IP retention clause — favorable to customer.',
      suggestions: [],
    },
    {
      clause_id: 'c-07',
      text: 'Payment is due net-30 from invoice date; late payments accrue 1.5% monthly interest.',
      page: 8,
      score: 5,
      category: 'payment',
      severity: 'medium',
      reasoning: 'Standard net-30 with moderate late fee; worth negotiating down.',
      suggestions: ['Negotiate late fee to 0.5% monthly or a flat fee.'],
    },
    {
      clause_id: 'c-08',
      text: 'Vendor may suspend services immediately upon payment default without notice.',
      page: 8,
      score: 8,
      category: 'payment',
      severity: 'high',
      reasoning: 'Immediate suspension without cure period is operationally risky.',
      suggestions: ['Add a 10-day cure period before any service suspension.'],
    },
    {
      clause_id: 'c-09',
      text: 'Disputes shall be resolved by binding arbitration in Delaware.',
      page: 10,
      score: 5,
      category: 'liability',
      severity: 'medium',
      reasoning: 'Arbitration clause limits legal recourse.',
      suggestions: ['Negotiate for mutual jurisdiction selection.'],
    },
    {
      clause_id: 'c-10',
      text: 'Vendor provides 99.5% uptime SLA with service credits as sole remedy.',
      page: 11,
      score: 6,
      category: 'liability',
      severity: 'medium',
      reasoning: 'Service credits as sole remedy limits compensation options.',
      suggestions: ['Add right to terminate if SLA breached more than 3 times per quarter.'],
    },
    {
      clause_id: 'c-11',
      text: 'Vendor will implement industry-standard security measures.',
      page: 12,
      score: 4,
      category: 'data',
      severity: 'medium',
      reasoning: 'Industry-standard is vague; specific standards should be enumerated.',
      suggestions: ['Require SOC 2 Type II compliance and annual third-party audits.'],
    },
    {
      clause_id: 'c-12',
      text: 'This agreement is governed by the laws of the State of California.',
      page: 13,
      score: 2,
      category: 'liability',
      severity: 'low',
      reasoning: 'Standard governing law clause; no unusual risk.',
      suggestions: [],
    },
  ],
};